# Generated by Django 2.2 on 2020-08-30 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('is_stu', models.BooleanField(default=True)),
                ('branch', models.CharField(choices=[('puc', 'PUC'), ('cse', 'CSE'), ('mech', 'MECH'), ('chem', 'CHEM'), ('ece', 'ECE'), ('mme', 'MME'), ('civil', 'CIVIL')], default='cse', max_length=5)),
                ('year', models.CharField(choices=[('p1', 'P1'), ('p2', 'P2'), ('e1', 'E1'), ('e2', 'E2'), ('e3', 'E3'), ('e4', 'E4')], default='e1', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='olms.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=999)),
                ('proof', models.FileField(default=None, upload_to='')),
                ('status', models.CharField(choices=[('1', 'submitted'), ('2', 'granted'), ('3', 'rejected')], default='1', max_length=9)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='olms.UserProfile')),
            ],
        ),
    ]
