# Generated by Django 2.2 on 2020-08-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_stu',
            new_name='is_admin',
        ),
        migrations.AddField(
            model_name='leaves',
            name='description',
            field=models.CharField(default=None, max_length=999),
        ),
        migrations.AddField(
            model_name='leaves',
            name='proof',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='leaves',
            name='reason',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('1', 'submitted'), ('2', 'granted'), ('3', 'rejected')], default='1', max_length=9),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
