# Generated by Django 2.2 on 2020-08-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0002_auto_20200830_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='in_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='leaves',
            name='out_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('granted', 'granted'), ('rejected', 'rejected')], default='submitted', max_length=9),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='olms.UserProfile'),
        ),
    ]
