# Generated by Django 2.2 on 2020-08-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0003_auto_20200830_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='in_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='out_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
