# Generated by Django 3.1 on 2020-08-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0004_auto_20200830_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='olms.userprofile', unique=True),
        ),
    ]
