# Generated by Django 3.1 on 2020-08-31 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0005_auto_20200830_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaveuser', to='olms.userprofile', unique=True),
        ),
    ]
