# Generated by Django 3.1 on 2020-08-31 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0006_auto_20200831_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='count',
        ),
        migrations.CreateModel(
            name='LeaveCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='olms.userprofile')),
            ],
        ),
    ]
