# Generated by Django 3.1 on 2020-09-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0008_auto_20200831_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to='proofs/'),
        ),
    ]
