# Generated by Django 3.1 on 2020-09-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0012_auto_20200901_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('security', 'Security')], default='stu', max_length=8),
        ),
    ]
