# Generated by Django 3.1 on 2020-09-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0013_auto_20200903_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('security', 'Security')], default='student', max_length=8),
        ),
    ]
