# Generated by Django 3.1 on 2020-09-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0014_auto_20200903_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='in_campus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('granted', 'granted'), ('rejected', 'rejected'), ('on_leave', 'On Leave'), ('completed', 'Completed')], default='pending', max_length=9),
        ),
    ]
