# Generated by Django 3.1 on 2020-09-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0015_auto_20200903_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('aadhar_no', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField()),
                ('Parent_name', models.CharField(max_length=50)),
                ('Parent_phn_no', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=30)),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='olms.userprofile')),
            ],
        ),
    ]
