# Generated by Django 3.1 on 2020-09-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0016_personal_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id',
            new_name='uid',
        ),
    ]
