# Generated by Django 3.1 on 2020-09-15 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0017_auto_20200915_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to='proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png', 'xlsx', 'xls'])]),
        ),
    ]
