# Generated by Django 3.1 on 2020-09-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0018_auto_20200915_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='remark',
            field=models.CharField(default='No remark', max_length=100),
        ),
    ]
