# Generated by Django 3.1 on 2020-09-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0019_leaves_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='actual_in_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='leaves',
            name='actual_out_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
